### ISSUE TITLE
Trouble getting csu_radartools from conda-forge

### ISSUE THREAD

**Issue by salbenson** [CSU-Radarmet/CSU_RadarTools#63]
Hi, 
I am working with c-band radar and am interested in using the csu_radartools.  I tried: 
conda install -c defaults -c conda-forge csu_radartools
and 
conda install -c tjlangco csu_radartools from https://anaconda.org/tjlangco/csu_radartools
I was unsuccessful in locating the csu_radartools package.  My error was:
PackagesNotFoundError: The following packages are not available from current channels:
 - csu_radartools

Any help is appreciated. Thanks!
Sally

**Comment by tjlang** [comment]
I apologize, the conda/pip installation was never fully fleshed out. We recommend that you compile directly from the source code. I will fix the README.

**Comment by tjlang** [comment]
README has been updated.

**Comment by salbenson** [comment]
Thanks.  I'll give that a try.

**Comment by salbenson** [comment]
Thanks.  I’ll give that a try.

On Jan 27, 2020, at 2:13 PM, Timothy Lang <notifications@github.com<mailto:notifications@github.com>> wrote:


I apologize, the conda/pip installation was never fully fleshed out. We recommend that you compile directly from the source code. I will fix the README.
